Update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,8 +2,27 @@
 
 # check presence of RepeatMasker and RepeatModeler
 echo "Checking RepeatMasker and RepeatModeler configuration"
-type RepeatMasker >/dev/null 2>&1 || { echo >&2 "Earl Grey requires RepeatMasker but it's not installed.  Aborting."; exit 1; }
-type RepeatModeler >/dev/null 2>&1 || { echo >&2 "Earl Grey requires RepeatMasker but it's not installed.  Aborting."; exit 1; }
+if [ -x "$(command -v RepeatMasker)" ]; then
+        echo "Success! RepeatMasker is installed and in PATH"
+else
+        echo "Error: RepeatMasker is not installed and in PATH"
+        exit 1
+fi
+
+if [ -x "$(command -v RepeatModeler)" ]; then
+        echo "Success! RepeatModeler is installed and in PATH"
+else
+        echo "Error: RepeatModeler is not installed and in PATH"
+        exit 1
+fi
+
+# create new conda environment
+
+conda env create -f ./earlGrey.yml
+
+# make Earl Grey Script executable
+
+chmod +x ./earlGrey
 
 # set paths in Earl Grey Script
 
@@ -17,11 +36,12 @@ sleep 3
 
 # Extract tRNAdb
 echo "Extracting zip archives"
-unzip ./scripts/bin/LTR_FINDER.x86_64-1.0.7/tRNAdb.zip
+tar -zxf ./scripts/bin/LTR_FINDER.x86_64-1.0.7/tRNAdb.tar.gz
 echo "Extracted required archives"
 sleep 3
 
 # Message Complete
 echo "Remember to activate the earl grey conda environment before running earlGrey"
 sleep 3
-echo "earlGrey command can be added to path to be run from any directory"
+export PATH=$PATH:$(realpath ./earlGrey)
+echo "earlGrey command has been added to path to be run from any directory"
