Update earlGreyLibConstruct
Add check for successful generation of TEstrainer library

diff --git a/earlGreyLibConstruct b/earlGreyLibConstruct
--- a/earlGreyLibConstruct
+++ b/earlGreyLibConstruct
@@ -3,7 +3,7 @@
 usage()
 {
         echo "  #############################
-        earlGrey version 4.4.4 (Library Construction Only)
+        earlGrey version 4.4.5 (Library Construction Only)
         Required Parameters:
                 -g == genome.fasta
                 -s == species name
@@ -164,7 +164,11 @@ strainer()
 sweepUp()
 {
         cd ${OUTDIR}/${species}_summaryFiles/
-        cp $latestFile ${OUTDIR}/${species}_summaryFiles/
+        if [ -s ${latestFile} ]; then
+                cp $latestFile ${OUTDIR}/${species}_summaryFiles/ 
+        else
+                echo "ERROR: TEstrainer failed to generate a TE library, please check logs" && exit 1
+        fi
 }
 
 # Subprocess runningTea 
