Add Error Catch for Bad FASTA Entries

diff --git a/earlGrey b/earlGrey
--- a/earlGrey
+++ b/earlGrey
@@ -164,6 +164,11 @@ BEE2()
 {
     cd ${OUTDIR}/${species}_ExtractAlign
     python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST.no_slash -l ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa.filtered.no_slash -lb $Flank -rb $Flank -n 20 -a n -t n -e n
+    if [ "(ls -A ${OUTDIR}/${species}_ExtractAlign/catTEfiles/)" ]; then
+    	continue
+    else
+    	echo "ERROR: extract_align.py was unable to run, please check logs and FASTA file for empty lines in the middle of entries (this is the main cause of failure)" && exit 1
+    fi
     mkdir ${OUTDIR}/${species}_ExtractAlign/mafft/ 
     parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/catTEfiles/*.fa 
     mkdir ${OUTDIR}/${species}_ExtractAlign/trimal/ && cd ${OUTDIR}/${species}_ExtractAlign/trimal/
