Update earlGreyLibConstruct

diff --git a/earlGreyLibConstruct b/earlGreyLibConstruct
--- a/earlGreyLibConstruct
+++ b/earlGreyLibConstruct
@@ -3,7 +3,7 @@
 usage()
 {
         echo "  #############################
-        earlGrey version 6.0.1 (Library Construction Only)
+        earlGrey version 6.0.2 (Library Construction Only)
         Required Parameters:
                 -g == genome.fasta
                 -s == species name
@@ -73,21 +73,21 @@ prepGenome()
 # Generate a copy of the RepeatMasker library subset used for the initial TE mask in FASTA format (only used if a RepeatMasker run is specified)
 getRepeatMaskerFasta()
 {
-        if [[ $RepSpec = *" "* ]]; then
-                echo "ERROR: You have entered a species name that contains a space, please use the NCBI TaxID rather than name. E.G In place of \"Homo sapiens\" use \"9606\""
-                exit 2
-        fi
-        if [[ $(which RepeatMasker) == *"bin"* ]]; then
-                libpath="$(which RepeatMasker | sed 's|bin/RepeatMasker|share/RepeatMasker/Libraries/RepeatMaskerLib.h5|')"
-        else
-                libpath="$(which RepeatMasker | sed 's|/[^/]*$||g')/Libraries/RepeatMaskerLib.h5"
-        fi
-        if [[ $(which RepeatMasker) == *"bin"* ]]; then
-                PATH=$PATH:"$(which RepeatMasker | sed 's|bin/RepeatMasker|share/RepeatMasker/|')"
-        fi
-        mkdir -p $OUTDIR/${species}_Curated_Library/
-        famdb.py -i $libpath families -f fasta_name --include-class-in-name -a -d $RepSpec > ${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
-        RepSub=${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
+	if [[ $RepSpec = *" "* ]]; then
+		echo "ERROR: You have entered a species name that contains a space, please use the NCBI TaxID rather than name. E.G In place of \"Homo sapiens\" use \"9606\""
+		exit 2
+	fi
+	if [[ $(which RepeatMasker) == *"bin"* ]]; then
+		libpath="$(which RepeatMasker | sed 's|bin/RepeatMasker|share/RepeatMasker/Libraries/famdb/|')"
+	else
+		libpath="$(which RepeatMasker | sed 's|/[^/]*$||g')/Libraries/famdb/"
+	fi
+	if [[ $(which RepeatMasker) == *"bin"* ]]; then
+		PATH=$PATH:"$(which RepeatMasker | sed 's|bin/RepeatMasker|share/RepeatMasker/|')"
+	fi
+	mkdir -p $OUTDIR/${species}_Curated_Library/
+	famdb.py -i $libpath families -f fasta_name --include-class-in-name -a -d $RepSpec > ${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
+	RepSub=${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
 }
 
 # Subprocess firstMask
@@ -275,7 +275,7 @@ Checks()
 	expected_file="${library_path}/dfam39_full.0.h5"
 	file_count=$(find "$library_path" -maxdepth 1 -type f | wc -l)
 	if [ $file_count -eq 2 ] && [ -f $expected_file ] && [ -f ${library_path}/rmlib.config ] ; then
-    		echo "WARNING: Earl Grey v6.0.1 has updated to Dfam v3.9." 
+    		echo "WARNING: Earl Grey v6.0.2 has updated to Dfam v3.9." 
     		echo "Before using Earl Grey, you MUST download the required partitions from Dfam (https://dfam.org/releases/current/families/FamDB/)"
     		echo "These must be located at ${library_path}/. Then, you must reconfigure RepeatMasker before using Earl Grey."
     		echo "I have written the required commands for you to faciliate the process."
