Update earlGrey

diff --git a/earlGrey b/earlGrey
--- a/earlGrey
+++ b/earlGrey
@@ -75,12 +75,11 @@ prepGenome()
 getRepeatMaskerFasta()
 {
     if [[ $RepSpec = *" "* ]]; then
-    	RepSpecFix=$(echo $RepSpec | sed 's/ //g')
-    else
-	RepSpecFix=$RepSpec
+    	echo "ERROR: You have entered a species name that contains a space, please use the NCBI TaxID rather than name. E.G In place of \"Homo sapiens\" use \"9606\""
+	exit 2
     fi
-    famdb.py -i $(which RepeatMasker | sed 's|/[^/]*$||g')/Libraries/RepeatMaskerLib.h5 families -f fasta_name --include-class-in-name -a -d $(echo "\""$RepSpec"\"") > ${OUTDIR}/${species}_Curated_Library/${RepSpecFix}.RepeatMasker.lib
-    RepSub=${OUTDIR}/${species}_Curated_Library/${RepSpecFix}.RepeatMasker.lib
+    famdb.py -i $(which RepeatMasker | sed 's|/[^/]*$||g')/Libraries/RepeatMaskerLib.h5 families -f fasta_name --include-class-in-name -a -d $RepSpec > ${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
+    RepSub=${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
 }
 
 # Subprocess firstMask
